/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssetsRouteImport } from './routes/assets'
import { Route as BillsRouteImport } from './routes/bills'
import { Route as BuffersRouteImport } from './routes/buffers'
import { Route as CopilotRouteImport } from './routes/copilot'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as EntitiesRouteImport } from './routes/entities'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as ForecastsRouteImport } from './routes/forecasts'
import { Route as InspectionsRouteImport } from './routes/inspections'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as RentalRouteImport } from './routes/rental'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as ApiCopilotRouteImport } from './routes/api/copilot'
import { Route as ApiVisionRouteImport } from './routes/api/vision'
import { Route as AssetsAssetIdRouteImport } from './routes/assets.$assetId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const BillsRoute = BillsRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => rootRouteImport,
} as any)
const BuffersRoute = BuffersRouteImport.update({
  id: '/buffers',
  path: '/buffers',
  getParentRoute: () => rootRouteImport,
} as any)
const CopilotRoute = CopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const EntitiesRoute = EntitiesRouteImport.update({
  id: '/entities',
  path: '/entities',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastsRoute = ForecastsRouteImport.update({
  id: '/forecasts',
  path: '/forecasts',
  getParentRoute: () => rootRouteImport,
} as any)
const InspectionsRoute = InspectionsRouteImport.update({
  id: '/inspections',
  path: '/inspections',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const RentalRoute = RentalRouteImport.update({
  id: '/rental',
  path: '/rental',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCopilotRoute = ApiCopilotRouteImport.update({
  id: '/api/copilot',
  path: '/api/copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVisionRoute = ApiVisionRouteImport.update({
  id: '/api/vision',
  path: '/api/vision',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsAssetIdRoute = AssetsAssetIdRouteImport.update({
  id: '/$assetId',
  path: '/$assetId',
  getParentRoute: () => AssetsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assets': typeof AssetsRouteWithChildren
  '/bills': typeof BillsRoute
  '/buffers': typeof BuffersRoute
  '/copilot': typeof CopilotRoute
  '/documents': typeof DocumentsRoute
  '/entities': typeof EntitiesRoute
  '/expenses': typeof ExpensesRoute
  '/forecasts': typeof ForecastsRoute
  '/inspections': typeof InspectionsRoute
  '/maintenance': typeof MaintenanceRoute
  '/portfolio': typeof PortfolioRoute
  '/rental': typeof RentalRoute
  '/settings': typeof SettingsRoute
  '/transactions': typeof TransactionsRoute
  '/api/copilot': typeof ApiCopilotRoute
  '/api/vision': typeof ApiVisionRoute
  '/assets/$assetId': typeof AssetsAssetIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assets': typeof AssetsRouteWithChildren
  '/bills': typeof BillsRoute
  '/buffers': typeof BuffersRoute
  '/copilot': typeof CopilotRoute
  '/documents': typeof DocumentsRoute
  '/entities': typeof EntitiesRoute
  '/expenses': typeof ExpensesRoute
  '/forecasts': typeof ForecastsRoute
  '/inspections': typeof InspectionsRoute
  '/maintenance': typeof MaintenanceRoute
  '/portfolio': typeof PortfolioRoute
  '/rental': typeof RentalRoute
  '/settings': typeof SettingsRoute
  '/transactions': typeof TransactionsRoute
  '/api/copilot': typeof ApiCopilotRoute
  '/api/vision': typeof ApiVisionRoute
  '/assets/$assetId': typeof AssetsAssetIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assets': typeof AssetsRouteWithChildren
  '/bills': typeof BillsRoute
  '/buffers': typeof BuffersRoute
  '/copilot': typeof CopilotRoute
  '/documents': typeof DocumentsRoute
  '/entities': typeof EntitiesRoute
  '/expenses': typeof ExpensesRoute
  '/forecasts': typeof ForecastsRoute
  '/inspections': typeof InspectionsRoute
  '/maintenance': typeof MaintenanceRoute
  '/portfolio': typeof PortfolioRoute
  '/rental': typeof RentalRoute
  '/settings': typeof SettingsRoute
  '/transactions': typeof TransactionsRoute
  '/api/copilot': typeof ApiCopilotRoute
  '/api/vision': typeof ApiVisionRoute
  '/assets/$assetId': typeof AssetsAssetIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assets'
    | '/bills'
    | '/buffers'
    | '/copilot'
    | '/documents'
    | '/entities'
    | '/expenses'
    | '/forecasts'
    | '/inspections'
    | '/maintenance'
    | '/portfolio'
    | '/rental'
    | '/settings'
    | '/transactions'
    | '/api/copilot'
    | '/api/vision'
    | '/assets/$assetId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assets'
    | '/bills'
    | '/buffers'
    | '/copilot'
    | '/documents'
    | '/entities'
    | '/expenses'
    | '/forecasts'
    | '/inspections'
    | '/maintenance'
    | '/portfolio'
    | '/rental'
    | '/settings'
    | '/transactions'
    | '/api/copilot'
    | '/api/vision'
    | '/assets/$assetId'
  id:
    | '__root__'
    | '/'
    | '/assets'
    | '/bills'
    | '/buffers'
    | '/copilot'
    | '/documents'
    | '/entities'
    | '/expenses'
    | '/forecasts'
    | '/inspections'
    | '/maintenance'
    | '/portfolio'
    | '/rental'
    | '/settings'
    | '/transactions'
    | '/api/copilot'
    | '/api/vision'
    | '/assets/$assetId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssetsRoute: typeof AssetsRouteWithChildren
  BillsRoute: typeof BillsRoute
  BuffersRoute: typeof BuffersRoute
  CopilotRoute: typeof CopilotRoute
  DocumentsRoute: typeof DocumentsRoute
  EntitiesRoute: typeof EntitiesRoute
  ExpensesRoute: typeof ExpensesRoute
  ForecastsRoute: typeof ForecastsRoute
  InspectionsRoute: typeof InspectionsRoute
  MaintenanceRoute: typeof MaintenanceRoute
  PortfolioRoute: typeof PortfolioRoute
  RentalRoute: typeof RentalRoute
  SettingsRoute: typeof SettingsRoute
  TransactionsRoute: typeof TransactionsRoute
  ApiCopilotRoute: typeof ApiCopilotRoute
  ApiVisionRoute: typeof ApiVisionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bills': {
      id: '/bills'
      path: '/bills'
      fullPath: '/bills'
      preLoaderRoute: typeof BillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buffers': {
      id: '/buffers'
      path: '/buffers'
      fullPath: '/buffers'
      preLoaderRoute: typeof BuffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copilot': {
      id: '/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof CopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entities': {
      id: '/entities'
      path: '/entities'
      fullPath: '/entities'
      preLoaderRoute: typeof EntitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecasts': {
      id: '/forecasts'
      path: '/forecasts'
      fullPath: '/forecasts'
      preLoaderRoute: typeof ForecastsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspections': {
      id: '/inspections'
      path: '/inspections'
      fullPath: '/inspections'
      preLoaderRoute: typeof InspectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rental': {
      id: '/rental'
      path: '/rental'
      fullPath: '/rental'
      preLoaderRoute: typeof RentalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/copilot': {
      id: '/api/copilot'
      path: '/api/copilot'
      fullPath: '/api/copilot'
      preLoaderRoute: typeof ApiCopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vision': {
      id: '/api/vision'
      path: '/api/vision'
      fullPath: '/api/vision'
      preLoaderRoute: typeof ApiVisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets/$assetId': {
      id: '/assets/$assetId'
      path: '/$assetId'
      fullPath: '/assets/$assetId'
      preLoaderRoute: typeof AssetsAssetIdRouteImport
      parentRoute: typeof AssetsRoute
    }
  }
}

interface AssetsRouteChildren {
  AssetsAssetIdRoute: typeof AssetsAssetIdRoute
}

const AssetsRouteChildren: AssetsRouteChildren = {
  AssetsAssetIdRoute: AssetsAssetIdRoute,
}

const AssetsRouteWithChildren =
  AssetsRoute._addFileChildren(AssetsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssetsRoute: AssetsRouteWithChildren,
  BillsRoute: BillsRoute,
  BuffersRoute: BuffersRoute,
  CopilotRoute: CopilotRoute,
  DocumentsRoute: DocumentsRoute,
  EntitiesRoute: EntitiesRoute,
  ExpensesRoute: ExpensesRoute,
  ForecastsRoute: ForecastsRoute,
  InspectionsRoute: InspectionsRoute,
  MaintenanceRoute: MaintenanceRoute,
  PortfolioRoute: PortfolioRoute,
  RentalRoute: RentalRoute,
  SettingsRoute: SettingsRoute,
  TransactionsRoute: TransactionsRoute,
  ApiCopilotRoute: ApiCopilotRoute,
  ApiVisionRoute: ApiVisionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
