/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CopilotRouteImport } from './routes/copilot'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as RentalRouteImport } from './routes/rental'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ApiCopilotRouteImport } from './routes/api/copilot'
import { Route as ApiVisionRouteImport } from './routes/api/vision'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CopilotRoute = CopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const RentalRoute = RentalRouteImport.update({
  id: '/rental',
  path: '/rental',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCopilotRoute = ApiCopilotRouteImport.update({
  id: '/api/copilot',
  path: '/api/copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVisionRoute = ApiVisionRouteImport.update({
  id: '/api/vision',
  path: '/api/vision',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/copilot': typeof CopilotRoute
  '/expenses': typeof ExpensesRoute
  '/maintenance': typeof MaintenanceRoute
  '/portfolio': typeof PortfolioRoute
  '/rental': typeof RentalRoute
  '/settings': typeof SettingsRoute
  '/api/copilot': typeof ApiCopilotRoute
  '/api/vision': typeof ApiVisionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/copilot': typeof CopilotRoute
  '/expenses': typeof ExpensesRoute
  '/maintenance': typeof MaintenanceRoute
  '/portfolio': typeof PortfolioRoute
  '/rental': typeof RentalRoute
  '/settings': typeof SettingsRoute
  '/api/copilot': typeof ApiCopilotRoute
  '/api/vision': typeof ApiVisionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/copilot': typeof CopilotRoute
  '/expenses': typeof ExpensesRoute
  '/maintenance': typeof MaintenanceRoute
  '/portfolio': typeof PortfolioRoute
  '/rental': typeof RentalRoute
  '/settings': typeof SettingsRoute
  '/api/copilot': typeof ApiCopilotRoute
  '/api/vision': typeof ApiVisionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/copilot'
    | '/expenses'
    | '/maintenance'
    | '/portfolio'
    | '/rental'
    | '/settings'
    | '/api/copilot'
    | '/api/vision'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/copilot'
    | '/expenses'
    | '/maintenance'
    | '/portfolio'
    | '/rental'
    | '/settings'
    | '/api/copilot'
    | '/api/vision'
  id:
    | '__root__'
    | '/'
    | '/copilot'
    | '/expenses'
    | '/maintenance'
    | '/portfolio'
    | '/rental'
    | '/settings'
    | '/api/copilot'
    | '/api/vision'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CopilotRoute: typeof CopilotRoute
  ExpensesRoute: typeof ExpensesRoute
  MaintenanceRoute: typeof MaintenanceRoute
  PortfolioRoute: typeof PortfolioRoute
  RentalRoute: typeof RentalRoute
  SettingsRoute: typeof SettingsRoute
  ApiCopilotRoute: typeof ApiCopilotRoute
  ApiVisionRoute: typeof ApiVisionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copilot': {
      id: '/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof CopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rental': {
      id: '/rental'
      path: '/rental'
      fullPath: '/rental'
      preLoaderRoute: typeof RentalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/copilot': {
      id: '/api/copilot'
      path: '/api/copilot'
      fullPath: '/api/copilot'
      preLoaderRoute: typeof ApiCopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vision': {
      id: '/api/vision'
      path: '/api/vision'
      fullPath: '/api/vision'
      preLoaderRoute: typeof ApiVisionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CopilotRoute: CopilotRoute,
  ExpensesRoute: ExpensesRoute,
  MaintenanceRoute: MaintenanceRoute,
  PortfolioRoute: PortfolioRoute,
  RentalRoute: RentalRoute,
  SettingsRoute: SettingsRoute,
  ApiCopilotRoute: ApiCopilotRoute,
  ApiVisionRoute: ApiVisionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
